version: "3.9"

services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "software-engineering"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: steamgamesmy@mail.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"